apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: snyksast
inputs:
  orgname:
    required: true
  token:
    required: true
  language:
    required: false
outputs:
  critical-count:
    description: A string containing the number of Critical security findings discovered during the scan.
    value: ${{steps.snyksast.outputs.critical-count}}
  very-high-count:
    description: A string containing the number of Very High security findings discovered during the scan.
    value: ${{steps.snyksast.outputs.very-high-count}}
  high-count:
    description: A string containing the number of High security findings discovered during the scan.
    value: ${{steps.snyksast.outputs.high-count}}
  medium-count:
    description: A string containing the number of Medium security findings discovered during the scan.
    value: ${{steps.snyksast.outputs.medium-count}}
  low-count:
    description: A string containing the number of Low security findings discovered during the scan.
    value: ${{steps.snyksast.outputs.low-count}}
runs:
  using: composite
  steps:
    - id: snyksast
      name: snyksast
      # latest image
      uses: docker://public.ecr.aws/l7o7z1g8/actions/snyk-sast-actions:main-29c86037011c4f715d05ef1aae5c2a1f8dc061dd
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        STEP_ID: ${{ step.internal.id }}
        JOB_ID: ${{ job.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set +x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{ step.internal.id }}"   

         # fetch checkedout repo url and branch into assetIdentifier and profileIdentifier
        assetIdentifier=$(git config --get remote.origin.url)
        currentBranch=$(git branch | grep "*")
        profileIdentifier=${currentBranch:2}

        CONFIG_JSON='{\"metaInfo\":{\"url\":\"NA\",\"username\":\"${{ inputs.orgname }}\",\"password\":\"NA\",\"client_secret\":\"${{ inputs.token }}\",\"toolName\":\"snyksast\"},\"orchestratorInfo\":{\"assetType\":\"CODE\",\"assetIdentifier\":\"'
        CONFIG_JSON+=$assetIdentifier
        CONFIG_JSON+='\",\"profileIdentifier\":\"'
        CONFIG_JSON+=$profileIdentifier
        CONFIG_JSON+='\",\"language\":\"${{ inputs.language }}\"},\"metaInformation\":{\"actor\":\"SCM-Bot\",\"commit_id\":\"${{ cloudbees.scm.sha }}\",\"tenent_info\":\"NA\",\"scanner_type\":\"SAST\",\"pipeline_info\":{\"id\":\"04612\",\"name\":\"test_pipeline\",\"step_id\":\"04612_test_pipeline\"}}}'
        
        cd /
        set -x
        /bin/bash -c "java -jar ./executables/snyk-sast-analyzer.jar & while ! nc -z localhost 5001; do sleep 1; done && ./executables/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"
 
